# Generated by Django 4.1.1 on 2022-11-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
