# Generated by Django 4.1.1 on 2022-11-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_alter_district_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicantion',
        ),
    ]
