# Generated by Django 4.1.1 on 2022-11-06 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_delete_applicantion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='applicant/')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.PositiveBigIntegerField()),
                ('document_type', models.CharField(choices=[('adhar card', 'Adhar Card'), ('pan card', 'Pan Card'), ('voder id card', 'Voder Id Card'), ('driving license', 'Driving License'), ('ration card', 'Ration Card'), ('BPL', 'BPL'), ('passport', 'Passport')], max_length=100)),
                ('document_file', models.FileField(upload_to='applicant/')),
                ('address_type', models.CharField(choices=[('adhar card', 'Adhar Card'), ('pan card', 'Pan Card'), ('voder id card', 'Voder Id Card'), ('driving license', 'Driving License'), ('ration card', 'Ration Card'), ('BPL', 'BPL'), ('passport', 'Passport')], max_length=100)),
                ('address_front', models.FileField(upload_to='applicant/')),
                ('address_back', models.FileField(upload_to='applicant/')),
                ('owner_file', models.FileField(upload_to='applicant/')),
                ('district', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('panchayat', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('subdivision', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('connection_type', models.CharField(max_length=100)),
                ('tension_type', models.CharField(max_length=100)),
                ('tariff', models.CharField(max_length=100)),
                ('phase', models.PositiveBigIntegerField()),
                ('load', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Application',
            },
        ),
    ]
