# Generated by Django 4.1.1 on 2022-11-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
