# Generated by Django 4.1.1 on 2022-11-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0005_alter_application_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='division',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='panchayat',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='subdivision',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
