# Generated by Django 4.1.1 on 2022-11-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_alter_block_block_alter_division_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer.district'),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer.block'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer.subdivision'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer.division'),
        ),
        migrations.AlterField(
            model_name='village',
            name='panchayat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer.panchayat'),
        ),
    ]
