# Generated by Django 4.1.1 on 2022-11-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_alter_block_district_alter_panchayat_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
