# Generated by Django 4.1.1 on 2022-11-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0009_officer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='officer',
            table='Officer',
        ),
    ]
