# Generated by Django 4.1.1 on 2022-11-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0010_alter_officer_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applicant/'),
        ),
    ]
