# Generated by Django 4.1.1 on 2022-11-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0012_application_photo_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
