# Generated by Django 4.1.1 on 2022-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0013_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
