# Generated by Django 4.1.1 on 2022-11-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0024_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
    ]
