# Generated by Django 4.1.1 on 2022-11-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0029_user_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
