# Generated by Django 4.1.1 on 2022-11-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0031_officer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
