# Generated by Django 4.1.1 on 2022-11-21 13:45

import consumer.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0032_delete_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('division', models.CharField(max_length=100)),
                ('subdivision', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Officer',
            },
            bases=('consumer.user',),
            managers=[
                ('objects', consumer.manager.UserManage()),
            ],
        ),
    ]
