# Generated by Django 4.1.1 on 2022-11-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0033_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_defect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_submited',
            field=models.BooleanField(default=False),
        ),
    ]
