# Generated by Django 4.1.1 on 2022-11-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0035_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
