# Generated by Django 4.1.1 on 2022-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0037_rename_is_defect_application_is_defected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='action',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
