# Generated by Django 4.1.1 on 2022-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0038_verify_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
